name: build-image

on:
  workflow_call:
    inputs:
      repo-name:
        description: The name of the Docker repo
        required: true
        type: string
      tag:
        description: If no tag is given, it defaults to a name based on the branch and git sha (e.g. `my-branch-a1b2c3d`)
        required: false
        type: string
      working-directory:
        description: The directory from which to run the build
        required: false
        type: string
      publish:
        description: Whether to publish the image to the repository. Defaults to `false`
        required: false
        type: boolean
        default: false
      docker-username:
        description: The username to sign into the Docker registry with
        required: false
        type: string
    secrets:
      docker-access-token:
        description: The access token to sign into the Docker registry with
        required: false
    outputs:
      tag:
        description: "The tag for the image"
        value: ${{ jobs.build.outputs.tag }}
      image_name:
        description: "The full image name (including the tag)"
        value: ${{ jobs.build.outputs.image_name }}

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build-image.outputs.tag }}
      image_name: ${{ steps.build-image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.docker-access-token }}
          DOCKER_USERNAME: ${{ inputs.docker-username }}
      - uses: buildpacks/github-actions/setup-pack@v4.9.0
      - name: Build Image
        id: build-image
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TAG=${TAG:-"$GIT_BRANCH-$GIT_COMMIT"}
          IMAGE_NAME=$REPO_NAME:$TAG

          pack build $IMAGE_NAME --builder paketobuildpacks/builder:base

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working-directory }}
        env:
          REPO_NAME: ${{ inputs.repo-name }}
          TAG: ${{ inputs.tag }}
      - name: Publish
        if: ${{ inputs.publish }}
        run: docker push $IMAGE_NAME
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image_name }}
