name: build-image

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      tag:
        required: false
        type: string
      working-directory:
        required: false
        type: string
      publish:
        required: false
        type: boolean
        default: false
    secrets:
      docker-username:
        required: false
      docker-access-token:
        required: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.docker-username }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.docker-access-token }}
      - uses: buildpacks/github-actions/setup-pack@v4.9.0
      - name: Build Image
        id: build-image
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TAG=${TAG:-"$GIT_BRANCH-$GIT_COMMIT"}
          IMAGE_NAME=$REPO_NAME:$TAG

          pack build $IMAGE_NAME --builder paketobuildpacks/builder:base

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working-directory }}
        env:
          REPO_NAME: ${{ inputs.repo-name }}
          TAG: ${{ inputs.tag }}
      - name: Publish
        if: ${{ inputs.publish }}
        run: docker push $IMAGE_NAME
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image_name }}

