name: build-image

on:
  workflow_call:
    inputs:
      repo-name:
        description: The name of the Docker repo
        required: true
        type: string
      tag:
        description: If no tag is given, it defaults to a name based on the branch and git sha (e.g. `my-branch-a1b2c3d`)
        required: false
        type: string
      working-directory:
        description: The directory from which to run prepare commands. Also used as the build directory unless `build-directory` is also specified.
        required: false
        type: string
      build-directory:
        description: The directory to run the build from. Defaults to `working-directory` if not defined.
        required: false
        type: string
      prepare-cmd:
        description: Command to run before invoking the build. Run from `working-directory`.
        required: false
        type: string
      publish:
        description: Whether to publish the image to the repository. Defaults to `false`
        required: false
        type: boolean
        default: false
      docker-username:
        description: The username to sign into the Docker registry with
        required: false
        type: string
      cache-image:
        description: A remote cache image to use
        required: false
        type: string
      node-version-file:
        description: If you wish to pin a node version, the file it's specified in.
        required: false
        type: string
      run-dockerfile:
        description: Specify a run.Dockerfile to customise the run image
        required: false
        type: string
    secrets:
      docker-access-token:
        description: The access token to sign into the Docker registry with
        required: false
    outputs:
      tag:
        description: "The tag for the image"
        value: ${{ jobs.build.outputs.tag }}
      image_name:
        description: "The full image name (including the tag)"
        value: ${{ jobs.build.outputs.image_name }}

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build-image.outputs.tag }}
      image_name: ${{ steps.build-image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        if: ${{ inputs.node-version-file }}
        with:
          node-version-file: ${{ inputs.node-version-file }}
      - uses: pnpm/action-setup@v4
        if: ${{ inputs.node-version-file }}
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.docker-access-token }}
          DOCKER_USERNAME: ${{ inputs.docker-username }}
      - uses: buildpacks/github-actions/setup-pack@v4.9.0
      - name: Prepare Build
        run: ${{ inputs.prepare-cmd }}
        working-directory: ${{ inputs.working-directory }}
      - name: Build Image
        id: build-image
        run: |
          if [[ -n $RUN_DOCKERFILE ]]; then
            docker build -t $RUN_IMAGE -f run.Dockerfile .
          fi
        
          GIT_COMMIT=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TAG=${TAG:-"$GIT_BRANCH-$GIT_COMMIT"}
          IMAGE_NAME=$REPO_NAME:$TAG

          args=(
            --builder gcr.io/buildpacks/builder
          )

          if [[ $PUBLISH == 'true' ]]; then
            if [[ -n $CACHE_IMAGE ]]; then
              args+=(--cache-image $CACHE_IMAGE)
            fi
            args+=(--publish)
          fi

          if [[ -n $RUN_DOCKERFILE ]]; then
            args+=(--run-image $RUN_IMAGE)
          fi

          pack build $IMAGE_NAME "${args[@]}"

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.build-directory || inputs.working-directory }}
        env:
          REPO_NAME: ${{ inputs.repo-name }}
          TAG: ${{ inputs.tag }}
          CACHE_IMAGE: ${{ inputs.cache-image }}
          PUBLISH: ${{ inputs.publish }}
          RUN_DOCKERFILE: ${{ inputs.run-dockerfile }}
          RUN_IMAGE: "${{ inputs.repo-name }}-run"
